### ISSUE TITLE
Combined search of Offer fields

### ISSUE THREAD

**Issue by bresu** [bresu/buecherboerse#1]
Offers should be filterable by the query parameter "search=" and then the term is looked up in multiple fields of offers, including resolved/nested fields (like seller or book).

Valid queries are e.g:

"api/v1/offers?search=12341234" => returns all offers where this number is in one of the searchable fields
"api/v1/offers?search=@gmx.at" => returns all offers where this email suffix is used 
"api/v1/offers?search=matteo" => returns all offers where the term "matteo" is present in the searchable fields

Remark:
Only limited capabilites if not logged in. Search limited to: book + it's fields, price,

Question @matteioo: Should boolean fields also be searchable? like marked/ active? field-based filtering (?fieldName=) better?

**Comment by matteioo** [comment]
Boolean fields are not filtered through the combined search, but rather using additional filters like `offers?search=example&active=true`.

**Comment by bresu** [comment]
Done.

**Comment by bresu** [comment]
TODO: make fields that are non public not filterable when user not authenticated!

**Comment by bresu** [comment]
Done. @matteioo sollen bei field search (also ?fieldname=value) auch zB book__exam__name explizit suchbar sein? (sichtbarkeit egal, da das sowieso public ist). Derzeit sind nämlich nicht alle felder filterable

**Comment by matteioo** [comment]
> Done. @matteioo sollen bei field search (also ?fieldname=value) auch zB book__exam__name explizit suchbar sein? (sichtbarkeit egal, da das sowieso public ist). Derzeit sind nämlich nicht alle felder filterable

Wäre schön aber je nach Komplexität geringe Prio.

**Comment by bresu** [comment]
Done. Reopen issue if you want further field-filtering besides what is already implemented:

```
fields = {
      'book__isbn': ['exact'],
       'book__exam__name': ['icontains'],
       'price': ['exact', 'gt', 'lt', 'gte', 'lte'],
      'marked': ['exact'],
        }
```
