### ISSUE TITLE
Make field matriculationNumber optional

### ISSUE THREAD

**Issue by matteioo** [bresu/buecherboerse#10]
OG: "Make the field `matriculationNumber` optional, so that sellers without a matriculation number can be created and therefore associated with offers."

Leads to problems with adding sellers that are already in the database. Although this can be caught by the frontend I also want a database constraint.

**Comment by bresu** [comment]
Proposal: Make combination of email and matriculationNumber unique, so that it's impossible to set the same person twice.
Edge case being person with no matriculation Number and providing different email adresses.

**Comment by matteioo** [comment]
> Leads to problems with adding sellers that are already in the database. Although this can be caught by the frontend I also want a database constraint.

> Proposal: Make combination of email and matriculationNumber unique, so that it's impossible to set the same person twice.
Edge case being person with no matriculation Number and providing different email adresses.

How would this be a problem? Is the email not unique already?

**Comment by bresu** [comment]
It is, but people give us their univerisity email adresses, private email adresses etc.
But if you don't see an issue, we can do this easily

**Comment by bresu** [comment]
FIXED at commit 8cd5bf4
