### ISSUE TITLE
New endpoint for setting an offer to inactive

### ISSUE THREAD

**Issue by matteioo** [bresu/buecherboerse#5]
Add an endpoint `/offers/sell` which accepts a list of offers (in the body) in a POST-request which will then be set to inactive and therefore marked as sold.

If the list contains an already inactive offer, then no offer should be marked as inactive but a 4xx status code must be returned (possibly 409 - conflict).

**Comment by bresu** [comment]
Related question: what should be the outcome of a DELETE request on `offers/<id>` be?

**Comment by bresu** [comment]
@matteioo is it ok if you send the body in this format?

`
{
  "offers":[1,2,3]
}
`

**Comment by bresu** [comment]
Done
