### ISSUE TITLE
Setting inactive offer to active

### ISSUE THREAD

**Issue by matteioo** [bresu/buecherboerse#6]
Updating an inactive offer via a PUT/PATCH request to `/offers/<id>` should fail with a "403 - forbidden".

@bresu setting an inactive offer as active: should it only be possible to admins via the separate admin interface or also via the regular authenticated view?

**Comment by bresu** [comment]
Should not be possible with the regular authenticated view, also admins are strongly advised to just create a new offer instead of reactivating an already de-activated offer
