### ISSUE TITLE
Sorting, filtering, search

### ISSUE THREAD

**Issue by matteioo** [bresu/buecherboerse#8]
This issue collects the relevant fields regarding, sorting, filtering, combined search regarding the **Book** model. The findings in this issue are built upon the following model structure:
```ts
{
  "isbn": string,
  "exam": {
    "id": number,
    "name": string
  },
  "title": string,
  "authors": string,
  "maxPrice": string,
  "edition": number,
  "publisher": string
}
```

## Sorting
- `maxPrice`
- `edition`

### Open for discussion
- `title`
- `exam_name`

## Default sorting
1. `title` ASC
2. `edition` DESC
3. `maxPrice` ASC

## Filter
- `exam_name`
- `maxPrice`

### Open for discussion
- `authors`
- `publisher`

## Fields for combined search
- `icontains`: `isbn`, `exam__name`, `title`, `authors`
- `exact`: -

**Comment by bresu** [comment]
Nicely formatted issue, I have implemented everything, also "open for discussion"
